### ISSUE TITLE
webpack mapping issue on build

### ISSUE THREAD

**Issue by Keiwen** [adeptoas/sweet-modal-vue#42]
Hey there,
I just downloaded your project, run npm install then build-src, and i got a webpack issue:
`
Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator_validateMapping [as _validateMapping] (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:276:15)
    at SourceMapGenerator_addMapping [as addMapping] (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:110:12)
    at C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:72:17
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack-sources\node_modules\source-map\lib\source-map-consumer.js:157:14)
    at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:48:24)
    at SourceMapSource.node (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack-sources\lib\SourceMapSource.js:32:35)
    at SourceMapSource.proto.sourceAndMap (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack-sources\lib\SourceAndMapMixin.js:30:18)
    at getTaskForFile (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack\lib\SourceMapDevToolPlugin.js:33:30)
    at chunk.files.forEach.file (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack\lib\SourceMapDevToolPlugin.js:91:21)
    at Array.forEach (<anonymous>)
    at C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack\lib\SourceMapDevToolPlugin.js:89:18
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack\lib\SourceMapDevToolPlugin.js:88:12)
    at Compilation.applyPlugins1 (C:\nodejs\projects\sweet-modal-vue-master\node_modules\tapable\lib\Tapable.js:75:14)
    at self.applyPluginsAsync.err (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack\lib\Compilation.js:670:11)
    at next (C:\nodejs\projects\sweet-modal-vue-master\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.compilation.plugin (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack\lib\ProgressPlugin.js:119:6)
    at next (C:\nodejs\projects\sweet-modal-vue-master\node_modules\tapable\lib\Tapable.js:204:14)
    at Compilation.<anonymous> (C:\nodejs\projects\sweet-modal-vue-master\node_modules\babel-minify-webpack-plugin\dist\index.js:119:11)
    at Compilation.applyPluginsAsyncSeries (C:\nodejs\projects\sweet-modal-vue-master\node_modules\tapable\lib\Tapable.js:206:13)
    at self.applyPluginsAsync.err (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack\lib\Compilation.js:666:10)
    at next (C:\nodejs\projects\sweet-modal-vue-master\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.compilation.plugin.callback (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack\lib\ProgressPlugin.js:115:6)
    at Compilation.applyPluginsAsyncSeries (C:\nodejs\projects\sweet-modal-vue-master\node_modules\tapable\lib\Tapable.js:206:13)
    at sealPart2 (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack\lib\Compilation.js:662:9)
    at next (C:\nodejs\projects\sweet-modal-vue-master\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.compilation.plugin (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack\lib\ProgressPlugin.js:111:6)
    at Compilation.applyPluginsAsyncSeries (C:\nodejs\projects\sweet-modal-vue-master\node_modules\tapable\lib\Tapable.js:206:13)
    at Compilation.seal (C:\nodejs\projects\sweet-modal-vue-master\node_modules\webpack\lib\Compilation.js:605:8)
`
Yeah, I'm working on windows :)
Any idea? I didn't found anything on web so far and i'm quite bad at webpack things!

**Comment by Keiwen** [comment]
Hmmm works with devtool "eval" tho

**Comment by bluefirex** [comment]
Yeah I noticed issues with some devtool configuration options. I'm not sure why, though.

**Comment by KennetSundien** [comment]
In devDependencies add this line:
    "webpack-sources": "1.0.1",
